# Generated by Django 5.1 on 2026-05-12 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="covers/"),
                ),
                ("rating", models.FloatField(default=0)),
                ("play_duration", models.CharField(blank=True, max_length=50)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("official_intro", models.TextField(blank=True)),
                ("review", models.TextField(blank=True)),
                ("purchase_link", models.URLField(blank=True)),
                ("is_hot", models.BooleanField(default=False)),
                ("sort_weight", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("categories", models.ManyToManyField(blank=True, to="games.category")),
            ],
            options={
                "ordering": ["-sort_weight", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SimilarGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similar_games",
                        to="games.game",
                    ),
                ),
                (
                    "similar_game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "unique_together": {("game", "similar_game")},
            },
        ),
    ]
