# Generated by Django 5.1 on 2026-05-12 08:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="is_hot",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="game",
            name="rating",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="sort_weight",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="similargame",
            name="similar_game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="similar_to",
                to="games.game",
            ),
        ),
    ]
